import * as types from '../constants/ActionTypes'

export const changeToPing = () => ({ type: types.PING })
export const updateNumberCurrent = (number) => ({ type: types.UPDATE_NUMBER_CURRENT, number })
export const upNumber = () => ({ type: types.UP_NUMBER })
export const downNumber = () => ({ type: types.DOWN_NUMBER })
export const add = () => ({ type: types.EQUAL, operator: types.ADD })
export const substract = () => ({ type: types.EQUAL, operator: types.SUBSTRACT })
export const divide = () => ({ type: types.EQUAL, operator: types.DIVIDE })
export const reverse = () => ({ type: types.CUSTOM_INSIDE, custom: types.REVERSE })
export const squareRoot = () => ({ type: types.CUSTOM_INSIDE, custom: types.SQUARE_ROOT })
export const percent = () => ({ type: types.CUSTOM_INSIDE, custom: types.PERCENT })
export const multiply = () => ({ type: types.EQUAL, operator: types.MULTIPLY })
export const equal = (save = true) => ({ type: types.EQUAL, save })
export const restart = () => ({ type: types.RESTART, all: true })
export const deleted = () => ({ type: types.RESTART, all: false })
export const remove = () => ({ type: types.UPDATE_NUMBER_CURRENT, remove: true })
export const addNumber = (number) => ({ type: types.ADD_NUMBER, number })
export const editOperation = (operationCurrent) => ({ type: types.EDIT_OPERATION, operationCurrent })
export const loading = () => ({ type: types.LOADING })
